<?php

namespace ContainerVrQiXlM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AGEBIfCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AGEBIfC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AGEBIfC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ClientController::delete' => ['privates', '.service_locator.q74EK0j', 'get_ServiceLocator_Q74EK0jService', true],
            'App\\Controller\\ClientController::edit' => ['privates', '.service_locator.q74EK0j', 'get_ServiceLocator_Q74EK0jService', true],
            'App\\Controller\\ClientController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ClientController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ClientController::show' => ['privates', '.service_locator.lTbvCHw', 'get_ServiceLocator_LTbvCHwService', true],
            'App\\Controller\\CommandeController::delete' => ['privates', '.service_locator.iR5i4O4', 'get_ServiceLocator_IR5i4O4Service', true],
            'App\\Controller\\CommandeController::edit' => ['privates', '.service_locator.iR5i4O4', 'get_ServiceLocator_IR5i4O4Service', true],
            'App\\Controller\\CommandeController::exportPdf' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CommandeController::index' => ['privates', '.service_locator.Ecpu4I3', 'get_ServiceLocator_Ecpu4I3Service', true],
            'App\\Controller\\CommandeController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CommandeController::searchAjax' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CommandeController::show' => ['privates', '.service_locator.TqIg1ou', 'get_ServiceLocator_TqIg1ouService', true],
            'App\\Controller\\PaymentController::success' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\ProduitController::delete' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\ProduitController::edit' => ['privates', '.service_locator.mpriqUx', 'get_ServiceLocator_MpriqUxService', true],
            'App\\Controller\\ProduitController::index' => ['privates', '.service_locator.Ecpu4I3', 'get_ServiceLocator_Ecpu4I3Service', true],
            'App\\Controller\\ProduitController::new' => ['privates', '.service_locator.LNwsF6h', 'get_ServiceLocator_LNwsF6hService', true],
            'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.ViXcClx', 'get_ServiceLocator_ViXcClxService', true],
            'App\\Controller\\StoreController::addToCart' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\StoreController::confirmOrder' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\StoreController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\StoreController::newCommande' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ClientController:delete' => ['privates', '.service_locator.q74EK0j', 'get_ServiceLocator_Q74EK0jService', true],
            'App\\Controller\\ClientController:edit' => ['privates', '.service_locator.q74EK0j', 'get_ServiceLocator_Q74EK0jService', true],
            'App\\Controller\\ClientController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ClientController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ClientController:show' => ['privates', '.service_locator.lTbvCHw', 'get_ServiceLocator_LTbvCHwService', true],
            'App\\Controller\\CommandeController:delete' => ['privates', '.service_locator.iR5i4O4', 'get_ServiceLocator_IR5i4O4Service', true],
            'App\\Controller\\CommandeController:edit' => ['privates', '.service_locator.iR5i4O4', 'get_ServiceLocator_IR5i4O4Service', true],
            'App\\Controller\\CommandeController:exportPdf' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CommandeController:index' => ['privates', '.service_locator.Ecpu4I3', 'get_ServiceLocator_Ecpu4I3Service', true],
            'App\\Controller\\CommandeController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CommandeController:searchAjax' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CommandeController:show' => ['privates', '.service_locator.TqIg1ou', 'get_ServiceLocator_TqIg1ouService', true],
            'App\\Controller\\PaymentController:success' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\ProduitController:delete' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\ProduitController:edit' => ['privates', '.service_locator.mpriqUx', 'get_ServiceLocator_MpriqUxService', true],
            'App\\Controller\\ProduitController:index' => ['privates', '.service_locator.Ecpu4I3', 'get_ServiceLocator_Ecpu4I3Service', true],
            'App\\Controller\\ProduitController:new' => ['privates', '.service_locator.LNwsF6h', 'get_ServiceLocator_LNwsF6hService', true],
            'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.ViXcClx', 'get_ServiceLocator_ViXcClxService', true],
            'App\\Controller\\StoreController:addToCart' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\StoreController:confirmOrder' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\StoreController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\StoreController:newCommande' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ClientController::delete' => '?',
            'App\\Controller\\ClientController::edit' => '?',
            'App\\Controller\\ClientController::index' => '?',
            'App\\Controller\\ClientController::new' => '?',
            'App\\Controller\\ClientController::show' => '?',
            'App\\Controller\\CommandeController::delete' => '?',
            'App\\Controller\\CommandeController::edit' => '?',
            'App\\Controller\\CommandeController::exportPdf' => '?',
            'App\\Controller\\CommandeController::index' => '?',
            'App\\Controller\\CommandeController::new' => '?',
            'App\\Controller\\CommandeController::searchAjax' => '?',
            'App\\Controller\\CommandeController::show' => '?',
            'App\\Controller\\PaymentController::success' => '?',
            'App\\Controller\\ProduitController::delete' => '?',
            'App\\Controller\\ProduitController::edit' => '?',
            'App\\Controller\\ProduitController::index' => '?',
            'App\\Controller\\ProduitController::new' => '?',
            'App\\Controller\\ProduitController::show' => '?',
            'App\\Controller\\StoreController::addToCart' => '?',
            'App\\Controller\\StoreController::confirmOrder' => '?',
            'App\\Controller\\StoreController::index' => '?',
            'App\\Controller\\StoreController::newCommande' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ClientController:delete' => '?',
            'App\\Controller\\ClientController:edit' => '?',
            'App\\Controller\\ClientController:index' => '?',
            'App\\Controller\\ClientController:new' => '?',
            'App\\Controller\\ClientController:show' => '?',
            'App\\Controller\\CommandeController:delete' => '?',
            'App\\Controller\\CommandeController:edit' => '?',
            'App\\Controller\\CommandeController:exportPdf' => '?',
            'App\\Controller\\CommandeController:index' => '?',
            'App\\Controller\\CommandeController:new' => '?',
            'App\\Controller\\CommandeController:searchAjax' => '?',
            'App\\Controller\\CommandeController:show' => '?',
            'App\\Controller\\PaymentController:success' => '?',
            'App\\Controller\\ProduitController:delete' => '?',
            'App\\Controller\\ProduitController:edit' => '?',
            'App\\Controller\\ProduitController:index' => '?',
            'App\\Controller\\ProduitController:new' => '?',
            'App\\Controller\\ProduitController:show' => '?',
            'App\\Controller\\StoreController:addToCart' => '?',
            'App\\Controller\\StoreController:confirmOrder' => '?',
            'App\\Controller\\StoreController:index' => '?',
            'App\\Controller\\StoreController:newCommande' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
