<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \App\Entity\Client implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresseLivraison' => [parent::class, 'adresseLivraison', null, 16],
        "\0".parent::class."\0".'commandes' => [parent::class, 'commandes', null, 16],
        "\0".parent::class."\0".'idClient' => [parent::class, 'idClient', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        'adresseLivraison' => [parent::class, 'adresseLivraison', null, 16],
        'commandes' => [parent::class, 'commandes', null, 16],
        'idClient' => [parent::class, 'idClient', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
