<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Fournisseur extends \App\Entity\Fournisseur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'contact' => [parent::class, 'contact', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'idFournisseur' => [parent::class, 'idFournisseur', null, 16],
        "\0".parent::class."\0".'nomEntreprise' => [parent::class, 'nomEntreprise', null, 16],
        "\0".parent::class."\0".'produits' => [parent::class, 'produits', null, 16],
        'contact' => [parent::class, 'contact', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'idFournisseur' => [parent::class, 'idFournisseur', null, 16],
        'nomEntreprise' => [parent::class, 'nomEntreprise', null, 16],
        'produits' => [parent::class, 'produits', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
