<?php

namespace ContainerU8UNuE5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q74EK0jService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q74EK0j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q74EK0j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'client' => ['privates', '.errored..service_locator.q74EK0j.App\\Entity\\Client', NULL, 'Cannot autowire service ".service_locator.q74EK0j": it needs an instance of "App\\Entity\\Client" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'client' => 'App\\Entity\\Client',
            'entityManager' => '?',
        ]);
    }
}
