<?php

namespace ContainerXkrcPIU;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommande2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mb0q1ob.App\Entity\Commande' shared service.
     *
     * @return \App\Entity\Commande
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.mb0q1ob": it needs an instance of "App\\Entity\\Commande" but this type has been excluded in "config/services.yaml".');
    }
}
