<?php

namespace ContainerCQekzSt;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2rQGGFsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2rQGGFs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2rQGGFs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ClientController::index' => ['privates', '.service_locator.egipcEH.App\\Controller\\ClientController::index()', 'getClientControllerindexService', true],
            'App\\Controller\\ClientController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\ClientController::new()', 'getClientControllernewService', true],
            'App\\Controller\\ClientController::show' => ['privates', '.service_locator.0jUX5FG.App\\Controller\\ClientController::show()', 'getClientControllershowService', true],
            'App\\Controller\\ClientController::edit' => ['privates', '.service_locator.6agy0ro.App\\Controller\\ClientController::edit()', 'getClientControllereditService', true],
            'App\\Controller\\ClientController::delete' => ['privates', '.service_locator.6agy0ro.App\\Controller\\ClientController::delete()', 'getClientControllerdeleteService', true],
            'App\\Controller\\CommandeController::index' => ['privates', '.service_locator.egipcEH.App\\Controller\\CommandeController::index()', 'getCommandeControllerindexService', true],
            'App\\Controller\\CommandeController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\CommandeController::new()', 'getCommandeControllernewService', true],
            'App\\Controller\\CommandeController::show' => ['privates', '.service_locator.ikQfIPI.App\\Controller\\CommandeController::show()', 'getCommandeControllershowService', true],
            'App\\Controller\\CommandeController::edit' => ['privates', '.service_locator.mb0q1ob.App\\Controller\\CommandeController::edit()', 'getCommandeControllereditService', true],
            'App\\Controller\\CommandeController::delete' => ['privates', '.service_locator.mb0q1ob.App\\Controller\\CommandeController::delete()', 'getCommandeControllerdeleteService', true],
            'App\\Controller\\ProduitController::index' => ['privates', '.service_locator.egipcEH.App\\Controller\\ProduitController::index()', 'getProduitControllerindexService', true],
            'App\\Controller\\ProduitController::new' => ['privates', '.service_locator.mqZqLk1.App\\Controller\\ProduitController::new()', 'getProduitControllernewService', true],
            'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.1qsaO7R.App\\Controller\\ProduitController::show()', 'getProduitControllershowService', true],
            'App\\Controller\\ProduitController::edit' => ['privates', '.service_locator.DmEs6gO.App\\Controller\\ProduitController::edit()', 'getProduitControllereditService', true],
            'App\\Controller\\ProduitController::delete' => ['privates', '.service_locator.wkzzwmi.App\\Controller\\ProduitController::delete()', 'getProduitControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ClientController:index' => ['privates', '.service_locator.egipcEH.App\\Controller\\ClientController::index()', 'getClientControllerindexService', true],
            'App\\Controller\\ClientController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\ClientController::new()', 'getClientControllernewService', true],
            'App\\Controller\\ClientController:show' => ['privates', '.service_locator.0jUX5FG.App\\Controller\\ClientController::show()', 'getClientControllershowService', true],
            'App\\Controller\\ClientController:edit' => ['privates', '.service_locator.6agy0ro.App\\Controller\\ClientController::edit()', 'getClientControllereditService', true],
            'App\\Controller\\ClientController:delete' => ['privates', '.service_locator.6agy0ro.App\\Controller\\ClientController::delete()', 'getClientControllerdeleteService', true],
            'App\\Controller\\CommandeController:index' => ['privates', '.service_locator.egipcEH.App\\Controller\\CommandeController::index()', 'getCommandeControllerindexService', true],
            'App\\Controller\\CommandeController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\CommandeController::new()', 'getCommandeControllernewService', true],
            'App\\Controller\\CommandeController:show' => ['privates', '.service_locator.ikQfIPI.App\\Controller\\CommandeController::show()', 'getCommandeControllershowService', true],
            'App\\Controller\\CommandeController:edit' => ['privates', '.service_locator.mb0q1ob.App\\Controller\\CommandeController::edit()', 'getCommandeControllereditService', true],
            'App\\Controller\\CommandeController:delete' => ['privates', '.service_locator.mb0q1ob.App\\Controller\\CommandeController::delete()', 'getCommandeControllerdeleteService', true],
            'App\\Controller\\ProduitController:index' => ['privates', '.service_locator.egipcEH.App\\Controller\\ProduitController::index()', 'getProduitControllerindexService', true],
            'App\\Controller\\ProduitController:new' => ['privates', '.service_locator.mqZqLk1.App\\Controller\\ProduitController::new()', 'getProduitControllernewService', true],
            'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.1qsaO7R.App\\Controller\\ProduitController::show()', 'getProduitControllershowService', true],
            'App\\Controller\\ProduitController:edit' => ['privates', '.service_locator.DmEs6gO.App\\Controller\\ProduitController::edit()', 'getProduitControllereditService', true],
            'App\\Controller\\ProduitController:delete' => ['privates', '.service_locator.wkzzwmi.App\\Controller\\ProduitController::delete()', 'getProduitControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ClientController::index' => '?',
            'App\\Controller\\ClientController::new' => '?',
            'App\\Controller\\ClientController::show' => '?',
            'App\\Controller\\ClientController::edit' => '?',
            'App\\Controller\\ClientController::delete' => '?',
            'App\\Controller\\CommandeController::index' => '?',
            'App\\Controller\\CommandeController::new' => '?',
            'App\\Controller\\CommandeController::show' => '?',
            'App\\Controller\\CommandeController::edit' => '?',
            'App\\Controller\\CommandeController::delete' => '?',
            'App\\Controller\\ProduitController::index' => '?',
            'App\\Controller\\ProduitController::new' => '?',
            'App\\Controller\\ProduitController::show' => '?',
            'App\\Controller\\ProduitController::edit' => '?',
            'App\\Controller\\ProduitController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ClientController:index' => '?',
            'App\\Controller\\ClientController:new' => '?',
            'App\\Controller\\ClientController:show' => '?',
            'App\\Controller\\ClientController:edit' => '?',
            'App\\Controller\\ClientController:delete' => '?',
            'App\\Controller\\CommandeController:index' => '?',
            'App\\Controller\\CommandeController:new' => '?',
            'App\\Controller\\CommandeController:show' => '?',
            'App\\Controller\\CommandeController:edit' => '?',
            'App\\Controller\\CommandeController:delete' => '?',
            'App\\Controller\\ProduitController:index' => '?',
            'App\\Controller\\ProduitController:new' => '?',
            'App\\Controller\\ProduitController:show' => '?',
            'App\\Controller\\ProduitController:edit' => '?',
            'App\\Controller\\ProduitController:delete' => '?',
        ]);
    }
}
