<?php

namespace ContainerCQekzSt;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wkzzwmi.App\Controller\ProduitController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wkzzwmi.App\\Controller\\ProduitController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'produit' => ['privates', '.errored..service_locator.wkzzwmi.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.wkzzwmi": it needs an instance of "App\\Entity\\Produit" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'produit' => 'App\\Entity\\Produit',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\ProduitController::delete()', $container);
    }
}
