<?php

namespace ContainerDHxVRi4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mb0q1ob.App\Controller\CommandeController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.mb0q1ob'] ?? $container->load('get_ServiceLocator_Mb0q1obService'));

        if (isset($container->privates['.service_locator.mb0q1ob.App\\Controller\\CommandeController::edit()'])) {
            return $container->privates['.service_locator.mb0q1ob.App\\Controller\\CommandeController::edit()'];
        }

        return $container->privates['.service_locator.mb0q1ob.App\\Controller\\CommandeController::edit()'] = $a->withContext('App\\Controller\\CommandeController::edit()', $container);
    }
}
