<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTEYKzZy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTEYKzZy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTEYKzZy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTEYKzZy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTEYKzZy\App_KernelDevDebugContainer([
    'container.build_hash' => 'TEYKzZy',
    'container.build_id' => 'fce72163',
    'container.build_time' => 1744317340,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTEYKzZy');
