<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU8UNuE5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU8UNuE5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU8UNuE5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU8UNuE5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU8UNuE5\App_KernelDevDebugContainer([
    'container.build_hash' => 'U8UNuE5',
    'container.build_id' => '62725d0f',
    'container.build_time' => 1746142386,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU8UNuE5');
